namespace BunnyTail.XamlProperty.Generator;

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;

using BunnyTail.XamlProperty.Generator.Models;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

using SourceGenerateHelper;

[Generator]
public sealed class AttachedPropertyGenerator : IIncrementalGenerator
{
    private const string AttributeLabel = "AttachedProperty";

    private const string PropertyAttributeName = "BunnyTail.XamlProperty.DependencyPropertyAttribute";

    private const string AttributeName = "BunnyTail.XamlProperty.AttachedPropertyAttribute";

    private const string AttributeSource =
        """
        // <auto-generated />
        #nullable enable

        namespace BunnyTail.XamlProperty;

        [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
        [global::System.AttributeUsage(global::System.AttributeTargets.Method)]
        internal sealed class AttachedPropertyAttribute : global::System.Attribute
        {
            public object? DefaultValue { get; set; }

            public string? DefaultValueExpression { get; set; }

            public string? DefaultValueMember { get; set; }

            public global::System.Windows.FrameworkPropertyMetadataOptions Options { get; set; }

            public string? PropertyChanged { get; set; }
        }
        """;

    private const string DependencyObjectTypeName = "System.Windows.DependencyObject";
    private const string PropertyChangedEventArgsTypeName = "System.Windows.DependencyPropertyChangedEventArgs";

    private const string DependencyPropertyTypeName = "global::System.Windows.DependencyProperty";
    private const string PropertyMetadataTypeName = "global::System.Windows.PropertyMetadata";
    private const string FrameworkPropertyMetadataTypeName = "global::System.Windows.FrameworkPropertyMetadata";

    private const string GetPrefix = "Get";
    private const string SetPrefix = "Set";

    private static readonly SymbolDisplayFormat TypeDisplayFormat = SymbolDisplayFormat.FullyQualifiedFormat
        .WithMiscellaneousOptions(SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions | SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    // ------------------------------------------------------------
    // Initialize
    // ------------------------------------------------------------

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static context =>
        {
            context.AddEmbeddedAttributeDefinition();
            context.AddSource("AttachedPropertyAttribute.g.cs", AttributeSource);
        });

        var propertyProvider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeName,
                static (syntax, _) => IsMethodSyntax(syntax),
                static (context, _) => GetAttachedPropertyModel(context))
            .Collect();

        var treeProvider = context.ForAttributeWithMetadataNameSyntaxTrees(
            AttributeName,
            static (syntax, _) => IsMethodSyntax(syntax));

        context.RegisterSourceOutput(
            propertyProvider.Combine(treeProvider),
            static (context, provider) => ReportDiagnostics(context, provider.Left, provider.Right));

        var typeProvider = propertyProvider.SelectMany(static (properties, _) => SelectTypeModel(properties));

        context.RegisterImplementationSourceOutput(
            typeProvider,
            static (context, type) => Execute(context, type));
    }

    private static ImmutableArray<AttachedTypeModel> SelectTypeModel(ImmutableArray<Result<AttachedPropertyModel>> properties)
    {
        var collisions = new HashSet<string>(FindHintNameCollisions(properties).Select(static x => x.HintName), StringComparer.Ordinal);
        return [.. properties
            .SelectValue()
            .Where(x => !collisions.Contains(MakeHintName(x.Namespace, x.ContainingTypes, x.ClassName)))
            .GroupBy(static x => new { x.Namespace, x.ClassName, x.ContainingTypes })
            .Select(static x => new AttachedTypeModel(
                x.Key.Namespace,
                x.Key.ClassName,
                x.Key.ContainingTypes,
                new EquatableArray<AttachedPropertyModel>(x)))];
    }

    private static string MakeHintName(string ns, EquatableArray<ContainingTypeModel> containingTypes, string className) =>
        HintNameBuilder.BuildWithExtension(ns, ".Attached.g.cs", [.. containingTypes.Select(static x => x.ClassName), className]);

    private static string MakeDisplayName(string ns, EquatableArray<ContainingTypeModel> containingTypes, string className) =>
        (String.IsNullOrEmpty(ns) ? string.Empty : ns + ".") + String.Join(".", containingTypes.Select(static x => x.ClassName).Append(className));

    private static List<(string HintName, string Name, string Other)> FindHintNameCollisions(ImmutableArray<Result<AttachedPropertyModel>> properties)
    {
        var collisions = new List<(string HintName, string Name, string Other)>();
        var firsts = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        var reported = new HashSet<string>(StringComparer.Ordinal);
        foreach (var (hintName, displayName) in properties
            .SelectValue()
            .Select(static x => (HintName: MakeHintName(x.Namespace, x.ContainingTypes, x.ClassName), DisplayName: MakeDisplayName(x.Namespace, x.ContainingTypes, x.ClassName)))
            .OrderBy(static x => x.HintName, StringComparer.Ordinal))
        {
            if (!firsts.TryGetValue(hintName, out var first))
            {
                firsts.Add(hintName, displayName);
            }
            else if ((first != displayName) && reported.Add(hintName))
            {
                collisions.Add((hintName, displayName, first));
            }
        }

        return collisions;
    }

    // ------------------------------------------------------------
    // Parser
    // ------------------------------------------------------------

    private static bool IsMethodSyntax(SyntaxNode syntax) =>
        syntax is MethodDeclarationSyntax;

    private static Result<AttachedPropertyModel> GetAttachedPropertyModel(GeneratorAttributeSyntaxContext context)
    {
        var syntax = (MethodDeclarationSyntax)context.TargetNode;
        if (context.TargetSymbol is not IMethodSymbol symbol)
        {
            return Results.Errors<AttachedPropertyModel>();
        }

        var location = syntax.Identifier.GetLocation();
        var compilation = context.SemanticModel.Compilation;
        var diagnostics = new List<DiagnosticInfo>();

        // Validate accessor definition
        if (!symbol.IsStatic ||
            !symbol.IsPartialDefinition ||
            symbol.IsGenericMethod ||
            symbol.ReturnsVoid ||
            symbol.ReturnsByRef ||
            symbol.ReturnsByRefReadonly ||
            (symbol.Parameters.Length != 1) ||
            !symbol.Name.StartsWith(GetPrefix, StringComparison.Ordinal) ||
            (symbol.Name.Length == GetPrefix.Length))
        {
            return CreateFallback(symbol, syntax, new DiagnosticInfo(Diagnostics.InvalidAccessorDefinition, location, symbol.Name));
        }

        // Validate containing type
        if (!IsExtendable(syntax, symbol.ContainingType))
        {
            return Results.Error<AttachedPropertyModel>(new DiagnosticInfo(Diagnostics.ContainingTypeNotPartial, location, AttributeLabel, symbol.Name));
        }

        var containingType = symbol.ContainingType;
        for (var type = containingType; type is not null; type = type.ContainingType)
        {
            if (type.IsGenericType)
            {
                return Results.Error<AttachedPropertyModel>(new DiagnosticInfo(Diagnostics.GenericTypeNotSupported, location, AttributeLabel, symbol.Name));
            }
        }

        var targetType = symbol.Parameters[0].Type;
        var isDependencyObject = false;
        for (var type = targetType; type is not null; type = type.BaseType)
        {
            if (type.HasFullyQualifiedMetadataName(DependencyObjectTypeName))
            {
                isDependencyObject = true;
                break;
            }
        }

        if (!isDependencyObject)
        {
            return CreateFallback(symbol, syntax, new DiagnosticInfo(Diagnostics.InvalidTargetType, location, symbol.Name));
        }

        var propertyName = symbol.Name.Substring(GetPrefix.Length);

        // Setter
        var setSignature = default(string);
        var setTargetName = string.Empty;
        var setValueName = string.Empty;
        var setTargetNullable = false;
        var isSetFallback = false;
        foreach (var method in containingType.GetMembers(SetPrefix + propertyName).OfType<IMethodSymbol>())
        {
            if (!method.IsPartialDefinition || (method.PartialImplementationPart is not null) ||
                (method.DeclaringSyntaxReferences.FirstOrDefault()?.GetSyntax() is not MethodDeclarationSyntax setSyntax))
            {
                continue;
            }

            setSignature = method.GetImplementationSignature(setSyntax);
            if (!method.IsStatic ||
                method.IsGenericMethod ||
                !method.ReturnsVoid ||
                (method.Parameters.Length != 2) ||
                !compilation.HasIdentityConversion(method.Parameters[0].Type, targetType) ||
                !compilation.HasIdentityConversion(method.Parameters[1].Type, symbol.ReturnType))
            {
                diagnostics.Add(new DiagnosticInfo(Diagnostics.InvalidSetterDefinition, location, method.Name));
                isSetFallback = true;
                break;
            }

            setTargetName = CSharpIdentifier.Escape(method.Parameters[0].Name);
            setValueName = CSharpIdentifier.Escape(method.Parameters[1].Name);
            setTargetNullable = method.Parameters[0].NullableAnnotation == NullableAnnotation.Annotated;
            break;
        }

        // Parse attribute
        var defaultValue = default(TypedConstant?);
        var defaultValueExpression = default(string);
        var defaultValueMember = default(string);
        var metadataOptions = default(string);
        var propertyChangedName = default(string);
        foreach (var argument in context.Attributes[0].NamedArguments)
        {
            switch (argument.Key)
            {
                case "DefaultValue":
                    defaultValue = argument.Value;
                    break;
                case "DefaultValueExpression":
                    defaultValueExpression = argument.Value.Value as string;
                    break;
                case "DefaultValueMember":
                    defaultValueMember = argument.Value.Value as string;
                    break;
                case "Options":
                    metadataOptions = argument.Value.ToCSharpExpression();
                    break;
                case "PropertyChanged":
                    propertyChangedName = argument.Value.Value as string;
                    break;
            }
        }

        // Default value
        var defaultValueCount = (defaultValue.HasValue ? 1 : 0) +
                                (String.IsNullOrEmpty(defaultValueExpression) ? 0 : 1) +
                                (String.IsNullOrEmpty(defaultValueMember) ? 0 : 1);
        var defaultValueLiteral = default(string);
        var usings = Array.Empty<string>();
        if (defaultValueCount > 1)
        {
            diagnostics.Add(new DiagnosticInfo(Diagnostics.DefaultValueConflict, location, AttributeLabel, symbol.Name));
        }
        else if (defaultValue.HasValue)
        {
            defaultValueLiteral = defaultValue.Value.TryToCSharpExpression(symbol.ReturnType, context.SemanticModel, syntax.SpanStart, out _)
                ? defaultValue.Value.ToCSharpExpression(symbol.ReturnType)
                : null;
            if (defaultValueLiteral is null)
            {
                diagnostics.Add(new DiagnosticInfo(Diagnostics.InvalidDefaultValue, location, AttributeLabel, symbol.Name));
            }
        }
        else if (!String.IsNullOrEmpty(defaultValueMember))
        {
            if (IsDefaultValueMember(compilation, containingType, defaultValueMember!, symbol.ReturnType))
            {
                defaultValueLiteral = defaultValueMember;
            }
            else
            {
                diagnostics.Add(new DiagnosticInfo(Diagnostics.InvalidDefaultValueMember, location, AttributeLabel, defaultValueMember!));
            }
        }
        else if (!String.IsNullOrEmpty(defaultValueExpression))
        {
            if (IsDefaultValueExpression(context.SemanticModel, syntax.SpanStart, defaultValueExpression!, symbol.ReturnType, out var castRequired))
            {
                defaultValueLiteral = castRequired ? "(" + symbol.ReturnType.ToDisplayString(TypeDisplayFormat) + ")(" + defaultValueExpression + ")" : defaultValueExpression;
                usings = CollectUsings(context.SemanticModel, syntax);
            }
            else
            {
                diagnostics.Add(new DiagnosticInfo(Diagnostics.InvalidDefaultValue, location, AttributeLabel, symbol.Name));
            }
        }

        // Callback (an invalid one is reported, and left out of the generated code)
        if (!String.IsNullOrEmpty(propertyChangedName) &&
            !IsPropertyChangedMethod(context.SemanticModel, syntax.SpanStart, containingType, propertyChangedName!, out var found))
        {
            diagnostics.Add(new DiagnosticInfo(
                found ? Diagnostics.InvalidCallbackMethod : Diagnostics.CallbackMethodNotFound, location, AttributeLabel, propertyChangedName!));
            propertyChangedName = null;
        }

        // Model
        var ns = String.IsNullOrEmpty(containingType.ContainingNamespace.Name)
            ? string.Empty
            : containingType.ContainingNamespace.ToDisplayString();

        var containingTypes = containingType.GetContainingTypes()
            .Select(static x => new ContainingTypeModel(x.GetClassName(), x.GetDeclarationKeyword()))
            .ToArray();

        var fieldName = propertyName + "Property";
        var valueType = symbol.ReturnType.ToDisplayString(TypeDisplayFormat);

        var fieldConflict = HasFieldConflict(
            containingType,
            fieldName,
            containingType.GetMembers(symbol.Name)
                .Where(x => !SymbolEqualityComparer.Default.Equals(x, symbol) && x.HasAttribute(AttributeName))
                .Concat(containingType.GetMembers(propertyName).Where(static x => x.HasAttribute(PropertyAttributeName))),
            syntax);
        if (fieldConflict)
        {
            diagnostics.Add(new DiagnosticInfo(Diagnostics.FieldNameConflict, location, AttributeLabel, fieldName));
        }

        var attachedModel = new AttachedPropertyModel(
            ns,
            containingType.GetClassName(),
            new EquatableArray<ContainingTypeModel>(containingTypes),
            containingType.GetDeclarationKeyword(),
            containingType.IsStatic,
            symbol.DeclaredAccessibility,
            symbol.GetImplementationSignature(syntax),
            CSharpIdentifier.Escape(symbol.Parameters[0].Name),
            setSignature,
            setTargetName,
            setValueName,
            propertyName,
            HidesBaseMember(compilation, containingType, fieldName, symbol.Name),
            targetType.ToDisplayString(TypeDisplayFormat),
            valueType,
            valueType.IndexOf('?') < 0 ? valueType : symbol.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            symbol.ReturnType.SpecialType != SpecialType.System_Object,
            defaultValueLiteral,
            metadataOptions,
            String.IsNullOrEmpty(propertyChangedName) ? null : propertyChangedName,
            new EquatableArray<string>(usings),
            fieldConflict,
            isSetFallback,
            symbol.Parameters[0].NullableAnnotation == NullableAnnotation.Annotated,
            setTargetNullable);

        return new Result<AttachedPropertyModel>(attachedModel, new EquatableArray<DiagnosticInfo>(diagnostics));
    }

    private static bool IsPropertyChangedMethod(SemanticModel semanticModel, int position, INamedTypeSymbol containingType, string methodName, out bool found)
    {
        found = false;
        foreach (var method in semanticModel.LookupSymbols(position, containingType, methodName).OfType<IMethodSymbol>())
        {
            found = true;

            if (method.IsStatic &&
                !method.IsGenericMethod &&
                method.ReturnsVoid &&
                (method.Parameters.Length == 2) &&
                method.Parameters[0].Type.HasFullyQualifiedMetadataName(DependencyObjectTypeName) &&
                method.Parameters[1].Type.HasFullyQualifiedMetadataName(PropertyChangedEventArgsTypeName))
            {
                return true;
            }
        }

        return false;
    }

    private static bool IsDefaultValueMember(Compilation compilation, INamedTypeSymbol containingType, string memberName, ITypeSymbol valueType)
    {
        foreach (var member in containingType.GetMembers(memberName))
        {
            var memberType = member switch
            {
                IFieldSymbol { IsStatic: true } field => field.Type,
                IPropertySymbol { IsStatic: true, GetMethod: not null } property => property.Type,
                _ => null
            };
            if ((memberType is not null) && IsDefaultValueType(compilation, memberType, valueType))
            {
                return true;
            }
        }

        return false;
    }

    private static bool IsDefaultValueType(Compilation compilation, ITypeSymbol valueType, ITypeSymbol propertyType)
    {
        var conversion = compilation.ClassifyConversion(valueType, propertyType);
        return conversion.IsImplicit && (conversion.IsIdentity || conversion.IsReference || conversion.IsBoxing || conversion.IsNullable);
    }

    private static bool HidesBaseMember(Compilation compilation, INamedTypeSymbol containingType, string fieldName, string sourceName)
    {
        for (var type = containingType.BaseType; type is not null; type = type.BaseType)
        {
            foreach (var member in type.GetMembers(fieldName))
            {
                if (compilation.IsSymbolAccessibleWithin(member, containingType))
                {
                    return true;
                }
            }

            foreach (var member in type.GetMembers(sourceName))
            {
                if (member.HasAttribute(AttributeName) && compilation.IsSymbolAccessibleWithin(member, containingType))
                {
                    return true;
                }
            }
        }

        return false;
    }

    // ------------------------------------------------------------
    // Generator
    // ------------------------------------------------------------

    private static void ReportDiagnostics(SourceProductionContext context, ImmutableArray<Result<AttachedPropertyModel>> properties, ImmutableArray<SyntaxTree> trees) =>
        context.ReportDiagnostics(
            properties.SelectError()
                .Concat(FindHintNameCollisions(properties).Select(static x => new DiagnosticInfo(Diagnostics.HintNameCollision, (Location?)null, AttributeLabel, x.Name, x.Other)))
                .Distinct(),
            trees);

    private static void Execute(SourceProductionContext context, AttachedTypeModel type)
    {
        context.CancellationToken.ThrowIfCancellationRequested();

        var builder = new SourceBuilder();
        BuildSource(builder, type);

        context.AddSource(MakeHintName(type.Namespace, type.ContainingTypes, type.ClassName), builder);
    }

    private static void BuildSource(SourceBuilder builder, AttachedTypeModel type)
    {
        var containingTypes = type.ContainingTypes;

        builder.AutoGenerated();
        builder.EnableNullable();
        builder.Disable("CS0612, CS0618");
        builder.NewLine();

        var usings = type.Properties.SelectMany(static x => x.Usings).Distinct().ToList();
        if (usings.Count > 0)
        {
            foreach (var line in usings)
            {
                builder.AppendLine(line);
            }

            builder.NewLine();
        }

        if (!String.IsNullOrEmpty(type.Namespace))
        {
            builder.Namespace(type.Namespace);
            builder.NewLine();
        }

        foreach (var containingType in containingTypes)
        {
            builder
                .Indent()
                .Append("partial ")
                .Append(containingType.Keyword)
                .Append(" ")
                .Append(containingType.ClassName)
                .NewLine();
            builder.BeginScope();
        }

        builder.Indent();
        if (type.Properties[0].IsStaticClass)
        {
            builder.Append("static ");
        }

        builder.Append("partial ").Append(type.Properties[0].TypeKeyword).Append(' ').Append(type.ClassName).NewLine();
        builder.BeginScope();

        var first = true;
        foreach (var property in type.Properties)
        {
            if (first)
            {
                first = false;
            }
            else
            {
                builder.NewLine();
            }

            BuildProperty(builder, type.ClassName, property);
        }

        builder.EndScope();

        for (var i = 0; i < containingTypes.Count; i++)
        {
            builder.EndScope();
        }
    }

    private static void BuildProperty(SourceBuilder builder, string className, AttachedPropertyModel property)
    {
        if (property.IsFallback)
        {
            builder.Indent().Append(property.GetSignature).NewLine();
            builder.BeginScope();
            builder.Indent().Append("throw new global::System.InvalidOperationException();").NewLine();
            builder.EndScope();
            if (property.SetSignature is not null)
            {
                builder.NewLine();
                builder.Indent().Append(property.SetSignature).NewLine();
                builder.BeginScope();
                builder.Indent().Append("throw new global::System.InvalidOperationException();").NewLine();
                builder.EndScope();
            }

            return;
        }

        // field
        builder
            .Indent()
            .Append(property.GetAccessibility.ToText())
            .Append(property.IsNewField ? " new" : string.Empty)
            .Append(" static readonly ")
            .Append(DependencyPropertyTypeName)
            .Append(" ")
            .Append(property.PropertyName)
            .Append("Property = ")
            .Append(DependencyPropertyTypeName)
            .Append(".RegisterAttached(")
            .NewLine();
        builder.Indent().Append("    \"").Append(property.PropertyName).Append("\",").NewLine();
        builder.Indent().Append("    typeof(").Append(property.TypeofType).Append("),").NewLine();
        builder.Indent().Append("    typeof(").Append(className).Append(")");

        var arguments = MakeMetadataArguments(property);
        if (arguments.Count > 0)
        {
            builder.Append(",").NewLine();

            var metadataType = property.MetadataOptions is not null ? FrameworkPropertyMetadataTypeName : PropertyMetadataTypeName;
            if (arguments.Count == 1)
            {
                builder.Indent().Append("    new ").Append(metadataType).Append("(").Append(arguments[0]).Append(")");
            }
            else
            {
                builder.Indent().Append("    new ").Append(metadataType).Append("(").NewLine();
                for (var i = 0; i < arguments.Count; i++)
                {
                    builder.Indent().Append("        ").Append(arguments[i]);
                    if (i < arguments.Count - 1)
                    {
                        builder.Append(",").NewLine();
                    }
                }

                builder.Append(")");
            }
        }

        builder.Append(");").NewLine();
        builder.NewLine();

        // getter
        builder
            .Indent()
            .Append(property.GetSignature)
            .Append(" => ");
        if (property.RequireCast)
        {
            builder.Append("(").Append(property.ValueType).Append(")");
        }

        builder.Append(property.GetParameterName).Append(property.GetTargetNullable ? "!.GetValue(" : ".GetValue(").Append(property.PropertyName).Append("Property);").NewLine();

        // setter
        if (property.IsSetFallback)
        {
            builder.NewLine();
            builder.Indent().Append(property.SetSignature!).NewLine();
            builder.BeginScope();
            builder.Indent().Append("throw new global::System.InvalidOperationException();").NewLine();
            builder.EndScope();
        }
        else if (property.SetSignature is not null)
        {
            builder.NewLine();
            builder
                .Indent()
                .Append(property.SetSignature)
                .Append(" => ")
                .Append(property.SetTargetName)
                .Append(property.SetTargetNullable ? "!.SetValue(" : ".SetValue(")
                .Append(property.PropertyName)
                .Append("Property, ")
                .Append(property.SetValueName)
                .Append(");")
                .NewLine();
        }
    }

    private static List<string> MakeMetadataArguments(AttachedPropertyModel property)
    {
        var arguments = new List<string>();

        var hasDefaultValue = property.DefaultValue is not null;
        var useFramework = property.MetadataOptions is not null;

        if (!hasDefaultValue && !useFramework && (property.PropertyChanged is null))
        {
            return arguments;
        }

        if (!hasDefaultValue && !useFramework && (property.PropertyChanged is not null))
        {
            arguments.Add(property.PropertyChanged);
            return arguments;
        }

        arguments.Add(property.DefaultValue ?? $"default({property.ValueType})");

        if (useFramework)
        {
            arguments.Add(property.MetadataOptions!);
        }

        if (property.PropertyChanged is not null)
        {
            arguments.Add(property.PropertyChanged);
        }

        return arguments;
    }

    // ------------------------------------------------------------
    // Helper
    // ------------------------------------------------------------

    private static Result<AttachedPropertyModel> CreateFallback(IMethodSymbol symbol, MethodDeclarationSyntax syntax, DiagnosticInfo error)
    {
        var containingType = symbol.ContainingType;
        if (!symbol.IsPartialDefinition || (symbol.PartialImplementationPart is not null) || !IsExtendable(syntax, containingType))
        {
            return Results.Error<AttachedPropertyModel>(error);
        }

        var setSignature = default(string);
        if (symbol.Name.StartsWith(GetPrefix, StringComparison.Ordinal))
        {
            foreach (var method in containingType.GetMembers(SetPrefix + symbol.Name.Substring(GetPrefix.Length)).OfType<IMethodSymbol>())
            {
                if (method.IsPartialDefinition && (method.PartialImplementationPart is null) &&
                    (method.DeclaringSyntaxReferences.FirstOrDefault()?.GetSyntax() is MethodDeclarationSyntax setSyntax))
                {
                    setSignature = method.GetImplementationSignature(setSyntax);
                    break;
                }
            }
        }

        var ns = String.IsNullOrEmpty(containingType.ContainingNamespace.Name)
            ? string.Empty
            : containingType.ContainingNamespace.ToDisplayString();
        var containingTypes = containingType.GetContainingTypes()
            .Select(static x => new ContainingTypeModel(x.GetClassName(), x.GetDeclarationKeyword()))
            .ToArray();

        return new Result<AttachedPropertyModel>(
            new AttachedPropertyModel(
                ns,
                containingType.GetClassName(),
                new EquatableArray<ContainingTypeModel>(containingTypes),
                containingType.GetDeclarationKeyword(),
                containingType.IsStatic,
                symbol.DeclaredAccessibility,
                symbol.GetImplementationSignature(syntax),
                string.Empty,
                setSignature,
                string.Empty,
                string.Empty,
                symbol.Name,
                false,
                string.Empty,
                string.Empty,
                string.Empty,
                false,
                null,
                null,
                null,
                new EquatableArray<string>([]),
                true,
                true,
                false,
                false),
            new EquatableArray<DiagnosticInfo>([error]));
    }

    private static bool IsExtendable(SyntaxNode syntax, INamedTypeSymbol containingType)
    {
        for (var typeSyntax = syntax.Parent as TypeDeclarationSyntax; typeSyntax is not null; typeSyntax = typeSyntax.Parent as TypeDeclarationSyntax)
        {
            if (!typeSyntax.Modifiers.Any(static x => x.IsKind(SyntaxKind.PartialKeyword)))
            {
                return false;
            }
        }

        for (var type = containingType; type is not null; type = type.ContainingType)
        {
            if (type.IsFileLocal)
            {
                return false;
            }
        }

        return true;
    }

    private static bool IsDefaultValueExpression(SemanticModel semanticModel, int position, string text, ITypeSymbol valueType, out bool castRequired)
    {
        castRequired = false;
        var expression = SyntaxFactory.ParseExpression(text);
        if (expression.ContainsDiagnostics)
        {
            return false;
        }

        var conversion = semanticModel.ClassifyConversion(position, expression, valueType);
        if (!conversion.Exists || !conversion.IsImplicit)
        {
            return false;
        }

        castRequired = !(conversion.IsIdentity || conversion.IsReference || conversion.IsBoxing || conversion.IsNullable || conversion.IsNullLiteral || conversion.IsDefaultLiteral);
        return true;
    }

    private static string[] CollectUsings(SemanticModel semanticModel, SyntaxNode syntax)
    {
        var usings = new List<string>();
        foreach (var node in syntax.AncestorsAndSelf())
        {
            var directives = node switch
            {
                CompilationUnitSyntax unit => unit.Usings,
                BaseNamespaceDeclarationSyntax ns => ns.Usings,
                _ => default
            };
            foreach (var directive in directives)
            {
                if (!directive.GlobalKeyword.IsKind(SyntaxKind.None))
                {
                    continue;
                }

                var line = directive switch
                {
                    { Alias: not null } => semanticModel.GetDeclaredSymbol(directive) is { } alias
                        ? $"using {directive.Alias.Name.Identifier.Text} = {alias.Target.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)};"
                        : null,
                    _ => semanticModel.GetSymbolInfo(directive.NamespaceOrType).Symbol is { } target
                        ? $"using {(directive.StaticKeyword.IsKind(SyntaxKind.None) ? string.Empty : "static ")}{target.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)};"
                        : null
                };
                if ((line is not null) && !usings.Contains(line))
                {
                    usings.Add(line);
                }
            }
        }

        return [.. usings];
    }

    private static bool HasFieldConflict(INamedTypeSymbol containingType, string fieldName, IEnumerable<ISymbol> others, SyntaxNode syntax)
    {
        if (!containingType.GetMembers(fieldName).IsEmpty)
        {
            return true;
        }

        foreach (var other in others)
        {
            var location = other.Locations.FirstOrDefault(static x => x.IsInSource);
            if (location?.SourceTree is null)
            {
                continue;
            }

            var order = String.CompareOrdinal(location.SourceTree.FilePath, syntax.SyntaxTree.FilePath);
            if ((order < 0) || ((order == 0) && (location.SourceSpan.Start < syntax.SpanStart)))
            {
                return true;
            }
        }

        return false;
    }
}
