namespace BunnyTail.XamlProperty.Generator;

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;

using BunnyTail.XamlProperty.Generator.Models;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

using SourceGenerateHelper;

[Generator]
public sealed class DependencyPropertyGenerator : IIncrementalGenerator
{
    private const string AttributeLabel = "DependencyProperty";

    private const string AttachedAttributeName = "BunnyTail.XamlProperty.AttachedPropertyAttribute";

    private const string GetPrefix = "Get";

    private const string AttributeName = "BunnyTail.XamlProperty.DependencyPropertyAttribute";

    private const string AttributeSource =
        """
        // <auto-generated />
        #nullable enable

        namespace BunnyTail.XamlProperty;

        [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
        [global::System.AttributeUsage(global::System.AttributeTargets.Property)]
        internal sealed class DependencyPropertyAttribute : global::System.Attribute
        {
            public object? DefaultValue { get; set; }

            public string? DefaultValueExpression { get; set; }

            public string? DefaultValueMember { get; set; }

            public global::System.Windows.FrameworkPropertyMetadataOptions Options { get; set; }

            public string? PropertyChanged { get; set; }

            public string? Coerce { get; set; }

            public string? Validate { get; set; }
        }
        """;

    private const string DependencyObjectTypeName = "System.Windows.DependencyObject";
    private const string PropertyChangedEventArgsTypeName = "System.Windows.DependencyPropertyChangedEventArgs";

    private const string DependencyPropertyTypeName = "global::System.Windows.DependencyProperty";
    private const string PropertyMetadataTypeName = "global::System.Windows.PropertyMetadata";
    private const string FrameworkPropertyMetadataTypeName = "global::System.Windows.FrameworkPropertyMetadata";

    private static readonly SymbolDisplayFormat TypeDisplayFormat = SymbolDisplayFormat.FullyQualifiedFormat
        .WithMiscellaneousOptions(SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions | SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    // ------------------------------------------------------------
    // Initialize
    // ------------------------------------------------------------

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static context =>
        {
            context.AddEmbeddedAttributeDefinition();
            context.AddSource("DependencyPropertyAttribute.g.cs", AttributeSource);
        });

        var propertyProvider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeName,
                static (syntax, _) => IsPropertySyntax(syntax),
                static (context, _) => GetPropertyModel(context))
            .Collect();

        var treeProvider = context.ForAttributeWithMetadataNameSyntaxTrees(
            AttributeName,
            static (syntax, _) => IsPropertySyntax(syntax));

        context.RegisterSourceOutput(
            propertyProvider.Combine(treeProvider),
            static (context, provider) => ReportDiagnostics(context, provider.Left, provider.Right));

        var typeProvider = propertyProvider.SelectMany(static (properties, _) => SelectTypeModel(properties));

        context.RegisterImplementationSourceOutput(
            typeProvider,
            static (context, type) => Execute(context, type));
    }

    private static ImmutableArray<TypeModel> SelectTypeModel(ImmutableArray<Result<PropertyModel>> properties)
    {
        var collisions = new HashSet<string>(FindHintNameCollisions(properties).Select(static x => x.HintName), StringComparer.Ordinal);
        return [.. properties
            .SelectValue()
            .Where(x => !collisions.Contains(MakeHintName(x.Namespace, x.ContainingTypes, x.ClassName)))
            .GroupBy(static x => new { x.Namespace, x.ClassName, x.ContainingTypes })
            .Select(static x => new TypeModel(
                x.Key.Namespace,
                x.Key.ClassName,
                x.Key.ContainingTypes,
                new EquatableArray<PropertyModel>(x)))];
    }

    private static string MakeHintName(string ns, EquatableArray<ContainingTypeModel> containingTypes, string className) =>
        HintNameBuilder.Build(ns, [.. containingTypes.Select(static x => x.ClassName), className]);

    private static string MakeDisplayName(string ns, EquatableArray<ContainingTypeModel> containingTypes, string className) =>
        (String.IsNullOrEmpty(ns) ? string.Empty : ns + ".") + String.Join(".", containingTypes.Select(static x => x.ClassName).Append(className));

    // Hint names are compared ignoring case, so of the types whose names differ only in case, only the first is generated
    private static List<(string HintName, string Name, string Other)> FindHintNameCollisions(ImmutableArray<Result<PropertyModel>> properties)
    {
        var collisions = new List<(string HintName, string Name, string Other)>();
        var firsts = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        var reported = new HashSet<string>(StringComparer.Ordinal);
        foreach (var (hintName, displayName) in properties
            .SelectValue()
            .Select(static x => (HintName: MakeHintName(x.Namespace, x.ContainingTypes, x.ClassName), DisplayName: MakeDisplayName(x.Namespace, x.ContainingTypes, x.ClassName)))
            .OrderBy(static x => x.HintName, StringComparer.Ordinal))
        {
            if (!firsts.TryGetValue(hintName, out var first))
            {
                firsts.Add(hintName, displayName);
            }
            else if ((first != displayName) && reported.Add(hintName))
            {
                collisions.Add((hintName, displayName, first));
            }
        }

        return collisions;
    }

    // ------------------------------------------------------------
    // Parser
    // ------------------------------------------------------------

    private static bool IsPropertySyntax(SyntaxNode syntax) =>
        syntax is PropertyDeclarationSyntax;

    private static Result<PropertyModel> GetPropertyModel(GeneratorAttributeSyntaxContext context)
    {
        var syntax = (PropertyDeclarationSyntax)context.TargetNode;
        if (context.TargetSymbol is not IPropertySymbol symbol)
        {
            return Results.Errors<PropertyModel>();
        }

        var location = syntax.Identifier.GetLocation();
        var diagnostics = new List<DiagnosticInfo>();

        // Validate property definition
        if (symbol.IsStatic)
        {
            return Results.Error<PropertyModel>(new DiagnosticInfo(Diagnostics.StaticPropertyNotSupported, location, symbol.Name));
        }

        if (!symbol.IsPartialDefinition || !syntax.Modifiers.Any(static x => x.IsKind(SyntaxKind.PartialKeyword)))
        {
            return Results.Error<PropertyModel>(new DiagnosticInfo(Diagnostics.InvalidPropertyDefinition, location, symbol.Name));
        }

        if ((symbol.GetMethod is null) || (symbol.SetMethod is null) ||
            symbol.SetMethod.IsInitOnly ||
            (symbol.GetMethod.DeclaredAccessibility != symbol.DeclaredAccessibility) ||
            (symbol.SetMethod.DeclaredAccessibility != symbol.DeclaredAccessibility))
        {
            return Results.Error<PropertyModel>(new DiagnosticInfo(Diagnostics.InvalidPropertyAccessor, location, symbol.Name));
        }

        // Validate containing type (the generated part of a file-local type would be another type)
        if (!IsExtendable(syntax, symbol.ContainingType))
        {
            return Results.Error<PropertyModel>(new DiagnosticInfo(Diagnostics.ContainingTypeNotPartial, location, AttributeLabel, symbol.Name));
        }

        var containingType = symbol.ContainingType;
        for (var type = containingType; type is not null; type = type.ContainingType)
        {
            if (type.IsGenericType)
            {
                return Results.Error<PropertyModel>(new DiagnosticInfo(Diagnostics.GenericTypeNotSupported, location, AttributeLabel, symbol.Name));
            }
        }

        // A struct or a record cannot derive from the property host type
        if ((containingType.TypeKind != TypeKind.Class) || containingType.IsRecord)
        {
            return Results.Error<PropertyModel>(new DiagnosticInfo(Diagnostics.InvalidContainingType, location, symbol.Name));
        }

        // The base type can be declared in another partial declaration, such as one generated from XAML,
        // so the check is skipped when the type has no explicit base type
        if (containingType.BaseType is { SpecialType: not SpecialType.System_Object } declaredBaseType)
        {
            var isDependencyObject = false;
            for (var baseType = declaredBaseType; baseType is not null; baseType = baseType.BaseType)
            {
                if (baseType.HasFullyQualifiedMetadataName(DependencyObjectTypeName))
                {
                    isDependencyObject = true;
                    break;
                }
            }

            if (!isDependencyObject)
            {
                return Results.Error<PropertyModel>(new DiagnosticInfo(Diagnostics.InvalidContainingType, location, symbol.Name));
            }
        }

        // Parse attribute
        var defaultValue = default(TypedConstant?);
        var defaultValueExpression = default(string);
        var defaultValueMember = default(string);
        var metadataOptions = default(string);
        var propertyChangedName = default(string);
        var coerceName = default(string);
        var validateName = default(string);
        foreach (var argument in context.Attributes[0].NamedArguments)
        {
            switch (argument.Key)
            {
                case "DefaultValue":
                    defaultValue = argument.Value;
                    break;
                case "DefaultValueExpression":
                    defaultValueExpression = argument.Value.Value as string;
                    break;
                case "DefaultValueMember":
                    defaultValueMember = argument.Value.Value as string;
                    break;
                case "Options":
                    metadataOptions = argument.Value.ToCSharpExpression();
                    break;
                case "PropertyChanged":
                    propertyChangedName = argument.Value.Value as string;
                    break;
                case "Coerce":
                    coerceName = argument.Value.Value as string;
                    break;
                case "Validate":
                    validateName = argument.Value.Value as string;
                    break;
            }
        }

        // Default value (an invalid one is reported, and the value is left out of the generated code)
        var defaultValueCount = (defaultValue.HasValue ? 1 : 0) +
                                (String.IsNullOrEmpty(defaultValueExpression) ? 0 : 1) +
                                (String.IsNullOrEmpty(defaultValueMember) ? 0 : 1);
        var defaultValueLiteral = default(string);
        var usings = Array.Empty<string>();
        if (defaultValueCount > 1)
        {
            diagnostics.Add(new DiagnosticInfo(Diagnostics.DefaultValueConflict, location, AttributeLabel, symbol.Name));
        }
        else if (defaultValue.HasValue)
        {
            // The value must convert to the property type implicitly, so 1.5 for int and null for a value type are errors
            defaultValueLiteral = defaultValue.Value.TryToCSharpExpression(symbol.Type, context.SemanticModel, syntax.SpanStart, out _)
                ? defaultValue.Value.ToCSharpExpression(symbol.Type)
                : null;
            if (defaultValueLiteral is null)
            {
                diagnostics.Add(new DiagnosticInfo(Diagnostics.InvalidDefaultValue, location, AttributeLabel, symbol.Name));
            }
        }
        else if (!String.IsNullOrEmpty(defaultValueMember))
        {
            if (IsDefaultValueMember(context.SemanticModel.Compilation, containingType, defaultValueMember!, symbol.Type))
            {
                defaultValueLiteral = defaultValueMember;
            }
            else
            {
                diagnostics.Add(new DiagnosticInfo(Diagnostics.InvalidDefaultValueMember, location, AttributeLabel, defaultValueMember!));
            }
        }
        else if (!String.IsNullOrEmpty(defaultValueExpression))
        {
            // The expression is bound where the attribute is written, and the usings in effect there are copied, and a conversion that changes the boxed type is written as a cast
            if (IsDefaultValueExpression(context.SemanticModel, syntax.SpanStart, defaultValueExpression!, symbol.Type, out var castRequired))
            {
                defaultValueLiteral = castRequired ? "(" + symbol.Type.ToDisplayString(TypeDisplayFormat) + ")(" + defaultValueExpression + ")" : defaultValueExpression;
                usings = CollectUsings(context.SemanticModel, syntax);
            }
            else
            {
                diagnostics.Add(new DiagnosticInfo(Diagnostics.InvalidDefaultValue, location, AttributeLabel, symbol.Name));
            }
        }

        // Callback
        var propertyChanged = default(PropertyChangedModel);
        if (!String.IsNullOrEmpty(propertyChangedName))
        {
            var (model, error) = ResolvePropertyChanged(context.SemanticModel, syntax.SpanStart, containingType, propertyChangedName!, symbol.Type, location);
            if (error is not null)
            {
                diagnostics.Add(error);
            }
            else
            {
                propertyChanged = model;
            }
        }

        var coerce = default(CoerceModel);
        if (!String.IsNullOrEmpty(coerceName))
        {
            var (model, error) = ResolveCoerce(context.SemanticModel, syntax.SpanStart, containingType, coerceName!, symbol.Type, location);
            if (error is not null)
            {
                diagnostics.Add(error);
            }
            else
            {
                coerce = model;
            }
        }

        var validate = default(ValidateModel);
        if (!String.IsNullOrEmpty(validateName))
        {
            var (model, error) = ResolveValidate(context.SemanticModel, syntax.SpanStart, containingType, validateName!, symbol.Type, location);
            if (error is not null)
            {
                diagnostics.Add(error);
            }
            else
            {
                validate = model;
            }
        }

        // Model
        var ns = String.IsNullOrEmpty(containingType.ContainingNamespace.Name)
            ? string.Empty
            : containingType.ContainingNamespace.ToDisplayString();

        var containingTypes = containingType.GetContainingTypes()
            .Select(static x => new ContainingTypeModel(x.GetClassName(), x.GetDeclarationKeyword()))
            .ToArray();

        var fieldName = symbol.Name + "Property";
        var valueType = symbol.Type.ToDisplayString(TypeDisplayFormat);

        // A field name taken by another member gets only a throwing implementation
        var fieldConflict = HasFieldConflict(
            containingType,
            fieldName,
            containingType.GetMembers(GetPrefix + symbol.Name).Where(static x => x.HasAttribute(AttachedAttributeName)),
            syntax);
        if (fieldConflict)
        {
            diagnostics.Add(new DiagnosticInfo(Diagnostics.FieldNameConflict, location, AttributeLabel, fieldName));
        }

        var propertyModel = new PropertyModel(
            ns,
            containingType.GetClassName(),
            new EquatableArray<ContainingTypeModel>(containingTypes),
            symbol.DeclaredAccessibility,
            symbol.GetImplementationSignature(syntax),
            symbol.Name,
            HidesBaseMember(context.SemanticModel.Compilation, containingType, fieldName, symbol.Name),
            valueType,
            valueType.IndexOf('?') < 0 ? valueType : symbol.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            symbol.Type.SpecialType != SpecialType.System_Object,
            defaultValueLiteral,
            metadataOptions,
            propertyChanged,
            coerce,
            validate,
            new EquatableArray<string>(usings),
            fieldConflict);

        return new Result<PropertyModel>(propertyModel, new EquatableArray<DiagnosticInfo>(diagnostics));
    }

    private static (PropertyChangedModel? Model, DiagnosticInfo? Error) ResolvePropertyChanged(SemanticModel semanticModel, int position, INamedTypeSymbol containingType, string methodName, ITypeSymbol propertyType, Location location)
    {
        var compilation = semanticModel.Compilation;
        var found = false;
        var candidates = new List<PropertyChangedModel>();
        foreach (var method in EnumerateCallbackMethods(semanticModel, position, containingType, methodName))
        {
            found = true;

            if (method.IsGenericMethod || !method.ReturnsVoid)
            {
                continue;
            }

            // A method that matches PropertyChangedCallback is used as a method group
            if (method.IsStatic)
            {
                if ((method.Parameters.Length == 2) &&
                    method.Parameters[0].Type.HasFullyQualifiedMetadataName(DependencyObjectTypeName) &&
                    method.Parameters[1].Type.HasFullyQualifiedMetadataName(PropertyChangedEventArgsTypeName))
                {
                    candidates.Add(new PropertyChangedModel(methodName, true, false, string.Empty, string.Empty));
                }

                continue;
            }

            if (method.Parameters.Length == 0)
            {
                candidates.Add(new PropertyChangedModel(methodName, false, false, string.Empty, string.Empty));
            }
            else if ((method.Parameters.Length == 2) &&
                     compilation.HasIdentityConversion(method.Parameters[0].Type, propertyType) &&
                     compilation.HasIdentityConversion(method.Parameters[1].Type, propertyType))
            {
                candidates.Add(new PropertyChangedModel(
                    methodName,
                    false,
                    true,
                    method.Parameters[0].Type.ToDisplayString(TypeDisplayFormat),
                    method.Parameters[1].Type.ToDisplayString(TypeDisplayFormat)));
            }
        }

        if (candidates.Count == 1)
        {
            return (candidates[0], null);
        }

        return found
            ? (null, new DiagnosticInfo(Diagnostics.InvalidCallbackMethod, location, AttributeLabel, methodName))
            : (null, new DiagnosticInfo(Diagnostics.CallbackMethodNotFound, location, AttributeLabel, methodName));
    }

    private static (CoerceModel? Model, DiagnosticInfo? Error) ResolveCoerce(SemanticModel semanticModel, int position, INamedTypeSymbol containingType, string methodName, ITypeSymbol propertyType, Location location)
    {
        var compilation = semanticModel.Compilation;
        var found = false;
        var candidates = new List<CoerceModel>();
        foreach (var method in EnumerateCallbackMethods(semanticModel, position, containingType, methodName))
        {
            found = true;

            if (method.IsGenericMethod)
            {
                continue;
            }

            // A method that matches CoerceValueCallback is used as a method group
            if (method.IsStatic &&
                (method.Parameters.Length == 2) &&
                (method.ReturnType.SpecialType == SpecialType.System_Object) &&
                method.Parameters[0].Type.HasFullyQualifiedMetadataName(DependencyObjectTypeName) &&
                (method.Parameters[1].Type.SpecialType == SpecialType.System_Object))
            {
                candidates.Add(new CoerceModel(methodName, true, true, string.Empty));
                continue;
            }

            if ((method.Parameters.Length != 1) ||
                !compilation.HasIdentityConversion(method.Parameters[0].Type, propertyType) ||
                !compilation.HasIdentityConversion(method.ReturnType, propertyType))
            {
                continue;
            }

            candidates.Add(new CoerceModel(methodName, false, method.IsStatic, method.Parameters[0].Type.ToDisplayString(TypeDisplayFormat)));
        }

        if (candidates.Count == 1)
        {
            return (candidates[0], null);
        }

        return found
            ? (null, new DiagnosticInfo(Diagnostics.InvalidCallbackMethod, location, AttributeLabel, methodName))
            : (null, new DiagnosticInfo(Diagnostics.CallbackMethodNotFound, location, AttributeLabel, methodName));
    }

    private static (ValidateModel? Model, DiagnosticInfo? Error) ResolveValidate(SemanticModel semanticModel, int position, INamedTypeSymbol containingType, string methodName, ITypeSymbol propertyType, Location location)
    {
        var compilation = semanticModel.Compilation;
        var found = false;
        var candidates = new List<ValidateModel>();
        foreach (var method in EnumerateCallbackMethods(semanticModel, position, containingType, methodName))
        {
            found = true;

            if (!method.IsStatic || method.IsGenericMethod ||
                (method.Parameters.Length != 1) ||
                (method.ReturnType.SpecialType != SpecialType.System_Boolean))
            {
                continue;
            }

            // A method that matches ValidateValueCallback is used as a method group
            if (method.Parameters[0].Type.SpecialType == SpecialType.System_Object)
            {
                candidates.Add(new ValidateModel(methodName, true, string.Empty));
                continue;
            }

            if (!compilation.HasIdentityConversion(method.Parameters[0].Type, propertyType))
            {
                continue;
            }

            candidates.Add(new ValidateModel(methodName, false, method.Parameters[0].Type.ToDisplayString(TypeDisplayFormat)));
        }

        if (candidates.Count == 1)
        {
            return (candidates[0], null);
        }

        return found
            ? (null, new DiagnosticInfo(Diagnostics.InvalidCallbackMethod, location, AttributeLabel, methodName))
            : (null, new DiagnosticInfo(Diagnostics.CallbackMethodNotFound, location, AttributeLabel, methodName));
    }

    // The overloads that the name finds in the type as C# looks it up, where a member of another kind such as a delegate
    // field hides the base methods of the same name
    private static IEnumerable<IMethodSymbol> EnumerateCallbackMethods(SemanticModel semanticModel, int position, INamedTypeSymbol containingType, string methodName) =>
        semanticModel.LookupSymbols(position, containingType, methodName).OfType<IMethodSymbol>();

    // A default value member is a static field or property of the property type
    private static bool IsDefaultValueMember(Compilation compilation, INamedTypeSymbol containingType, string memberName, ITypeSymbol propertyType)
    {
        for (var type = containingType; type is not null; type = type.BaseType)
        {
            var declared = false;
            foreach (var member in type.GetMembers(memberName))
            {
                if (!compilation.IsSymbolAccessibleWithin(member, containingType))
                {
                    continue;
                }

                declared = true;

                var memberType = member switch
                {
                    IFieldSymbol { IsStatic: true } field => field.Type,
                    IPropertySymbol { IsStatic: true, GetMethod: not null } property => property.Type,
                    _ => null
                };
                if ((memberType is not null) && IsDefaultValueType(compilation, memberType, propertyType))
                {
                    return true;
                }
            }

            if (declared)
            {
                return false;
            }
        }

        return false;
    }

    // The value is boxed as it is, so a conversion must keep its runtime type
    private static bool IsDefaultValueType(Compilation compilation, ITypeSymbol valueType, ITypeSymbol propertyType)
    {
        var conversion = compilation.ClassifyConversion(valueType, propertyType);
        return conversion.IsImplicit && (conversion.IsIdentity || conversion.IsReference || conversion.IsBoxing || conversion.IsNullable);
    }

    // The field generated for a base type is not in the compilation, so the member it is generated for is looked at as well
    private static bool HidesBaseMember(Compilation compilation, INamedTypeSymbol containingType, string fieldName, string sourceName)
    {
        for (var type = containingType.BaseType; type is not null; type = type.BaseType)
        {
            foreach (var member in type.GetMembers(fieldName))
            {
                if (compilation.IsSymbolAccessibleWithin(member, containingType))
                {
                    return true;
                }
            }

            foreach (var member in type.GetMembers(sourceName))
            {
                if (member.HasAttribute(AttributeName) && compilation.IsSymbolAccessibleWithin(member, containingType))
                {
                    return true;
                }
            }
        }

        return false;
    }

    // ------------------------------------------------------------
    // Generator
    // ------------------------------------------------------------

    private static void ReportDiagnostics(SourceProductionContext context, ImmutableArray<Result<PropertyModel>> properties, ImmutableArray<SyntaxTree> trees) =>
        context.ReportDiagnostics(
            properties.SelectError()
                .Concat(FindHintNameCollisions(properties).Select(static x => new DiagnosticInfo(Diagnostics.HintNameCollision, (Location?)null, AttributeLabel, x.Name, x.Other)))
                .Distinct(),
            trees);

    private static void Execute(SourceProductionContext context, TypeModel type)
    {
        context.CancellationToken.ThrowIfCancellationRequested();

        var builder = new SourceBuilder();
        BuildSource(builder, type);

        context.AddSource(MakeHintName(type.Namespace, type.ContainingTypes, type.ClassName), builder);
    }

    private static void BuildSource(SourceBuilder builder, TypeModel type)
    {
        var ns = type.Namespace;
        var containingTypes = type.ContainingTypes;
        var className = type.ClassName;

        builder.AutoGenerated();
        builder.EnableNullable();
        builder.Disable("CS0612, CS0618");
        builder.NewLine();

        var usings = type.Properties.SelectMany(static x => x.Usings).Distinct().ToList();
        if (usings.Count > 0)
        {
            foreach (var line in usings)
            {
                builder.AppendLine(line);
            }

            builder.NewLine();
        }

        // namespace
        if (!String.IsNullOrEmpty(ns))
        {
            builder.Namespace(ns);
            builder.NewLine();
        }

        // containing types
        foreach (var containingType in containingTypes)
        {
            builder
                .Indent()
                .Append("partial ")
                .Append(containingType.Keyword)
                .Append(" ")
                .Append(containingType.ClassName)
                .NewLine();
            builder.BeginScope();
        }

        // class
        builder
            .Indent()
            .Append("partial class ")
            .Append(className)
            .NewLine();
        builder.BeginScope();

        var first = true;
        foreach (var property in type.Properties)
        {
            if (first)
            {
                first = false;
            }
            else
            {
                builder.NewLine();
            }

            BuildProperty(builder, className, property);
        }

        builder.EndScope();

        // end containing types
        for (var i = 0; i < containingTypes.Count; i++)
        {
            builder.EndScope();
        }
    }

    private static void BuildProperty(SourceBuilder builder, string className, PropertyModel property)
    {
        // Without the field, the property only throws
        if (property.IsFallback)
        {
            builder
                .Indent()
                .Append(property.Signature)
                .NewLine();
            builder.BeginScope();
            builder.Indent().Append("get => throw new global::System.InvalidOperationException();").NewLine();
            builder.Indent().Append("set => throw new global::System.InvalidOperationException();").NewLine();
            builder.EndScope();
            return;
        }

        var accessibility = property.PropertyAccessibility.ToText();

        // field
        builder
            .Indent()
            .Append(accessibility)
            .Append(property.IsNewField ? " new" : string.Empty)
            .Append(" static readonly ")
            .Append(DependencyPropertyTypeName)
            .Append(" ")
            .Append(property.PropertyName)
            .Append("Property = ")
            .Append(DependencyPropertyTypeName)
            .Append(".Register(")
            .NewLine();
        builder.Indent().Append("    nameof(").Append(CSharpIdentifier.Escape(property.PropertyName)).Append("),").NewLine();
        builder.Indent().Append("    typeof(").Append(property.TypeofType).Append("),").NewLine();
        builder.Indent().Append("    typeof(").Append(className).Append(")");

        var metadataArguments = MakeMetadataArguments(className, property);
        if (metadataArguments.Count > 0)
        {
            builder.Append(",").NewLine();

            var metadataType = property.MetadataOptions is not null ? FrameworkPropertyMetadataTypeName : PropertyMetadataTypeName;
            if (metadataArguments.Count == 1)
            {
                builder.Indent().Append("    new ").Append(metadataType).Append("(").Append(metadataArguments[0]).Append(")");
            }
            else
            {
                builder.Indent().Append("    new ").Append(metadataType).Append("(").NewLine();
                for (var i = 0; i < metadataArguments.Count; i++)
                {
                    builder.Indent().Append("        ").Append(metadataArguments[i]);
                    if (i < metadataArguments.Count - 1)
                    {
                        builder.Append(",").NewLine();
                    }
                }

                builder.Append(")");
            }
        }
        else if (property.Validate is not null)
        {
            builder.Append(",").NewLine();
            builder.Indent().Append("    null");
        }

        if (property.Validate is not null)
        {
            builder.Append(",").NewLine();
            builder.Indent().Append("    ");
            if (property.Validate.IsMethodGroup)
            {
                builder.Append(property.Validate.MethodName);
            }
            else
            {
                builder
                    .Append("static __value => ")
                    .Append(property.Validate.MethodName)
                    .Append("((")
                    .Append(property.Validate.ParameterType)
                    .Append(")__value)");
            }
        }

        builder.Append(");").NewLine();
        builder.NewLine();

        // property (the implementation repeats the declaration of the definition)
        builder
            .Indent()
            .Append(property.Signature)
            .NewLine();
        builder.BeginScope();
        builder.Indent().Append("get => ");
        if (property.RequireCast)
        {
            builder.Append("(").Append(property.PropertyType).Append(")");
        }

        builder.Append("GetValue(").Append(property.PropertyName).Append("Property);").NewLine();
        builder.Indent().Append("set => SetValue(").Append(property.PropertyName).Append("Property, value);").NewLine();
        builder.EndScope();
    }

    private static List<string> MakeMetadataArguments(string className, PropertyModel property)
    {
        var arguments = new List<string>();

        var hasDefaultValue = property.DefaultValue is not null;
        var useFramework = property.MetadataOptions is not null;
        var changed = property.PropertyChanged;
        var coerce = property.Coerce;

        if (!hasDefaultValue && !useFramework && (changed is null) && (coerce is null))
        {
            return arguments;
        }

        // PropertyMetadata(PropertyChangedCallback)
        if (!hasDefaultValue && !useFramework && (changed is not null) && (coerce is null))
        {
            arguments.Add(MakeChangedCallback(className, changed));
            return arguments;
        }

        arguments.Add(property.DefaultValue ?? $"default({property.PropertyType})");

        if (useFramework)
        {
            arguments.Add(property.MetadataOptions!);
        }

        if (changed is not null)
        {
            arguments.Add(MakeChangedCallback(className, changed));
        }
        else if (coerce is not null)
        {
            arguments.Add("null");
        }

        if (coerce is not null)
        {
            arguments.Add(MakeCoerceCallback(className, coerce));
        }

        return arguments;
    }

    private static string MakeChangedCallback(string className, PropertyChangedModel changed)
    {
        if (changed.IsMethodGroup)
        {
            return changed.MethodName;
        }

        return changed.HasParameters
            ? $"static (__d, __e) => (({className})__d).{changed.MethodName}(({changed.OldParameterType})__e.OldValue, ({changed.NewParameterType})__e.NewValue)"
            : $"static (__d, __e) => (({className})__d).{changed.MethodName}()";
    }

    private static string MakeCoerceCallback(string className, CoerceModel coerce)
    {
        if (coerce.IsMethodGroup)
        {
            return coerce.MethodName;
        }

        return coerce.IsStatic
            ? $"static (__d, __baseValue) => {coerce.MethodName}(({coerce.ParameterType})__baseValue)"
            : $"static (__d, __baseValue) => (({className})__d).{coerce.MethodName}(({coerce.ParameterType})__baseValue)";
    }

    // ------------------------------------------------------------
    // Helper
    // ------------------------------------------------------------

    private static bool IsExtendable(SyntaxNode syntax, INamedTypeSymbol containingType)
    {
        for (var typeSyntax = syntax.Parent as TypeDeclarationSyntax; typeSyntax is not null; typeSyntax = typeSyntax.Parent as TypeDeclarationSyntax)
        {
            if (!typeSyntax.Modifiers.Any(static x => x.IsKind(SyntaxKind.PartialKeyword)))
            {
                return false;
            }
        }

        for (var type = containingType; type is not null; type = type.ContainingType)
        {
            if (type.IsFileLocal)
            {
                return false;
            }
        }

        return true;
    }

    // The expression must convert to the value type where the attribute is written
    private static bool IsDefaultValueExpression(SemanticModel semanticModel, int position, string text, ITypeSymbol valueType, out bool castRequired)
    {
        castRequired = false;
        var expression = SyntaxFactory.ParseExpression(text);
        if (expression.ContainsDiagnostics)
        {
            return false;
        }

        var conversion = semanticModel.ClassifyConversion(position, expression, valueType);
        if (!conversion.Exists || !conversion.IsImplicit)
        {
            return false;
        }

        castRequired = !(conversion.IsIdentity || conversion.IsReference || conversion.IsBoxing || conversion.IsNullable || conversion.IsNullLiteral || conversion.IsDefaultLiteral);
        return true;
    }

    // The usings in effect at the declaration, written to the generated file with their targets fully qualified
    private static string[] CollectUsings(SemanticModel semanticModel, SyntaxNode syntax)
    {
        var usings = new List<string>();
        foreach (var node in syntax.AncestorsAndSelf())
        {
            var directives = node switch
            {
                CompilationUnitSyntax unit => unit.Usings,
                BaseNamespaceDeclarationSyntax ns => ns.Usings,
                _ => default
            };
            foreach (var directive in directives)
            {
                if (!directive.GlobalKeyword.IsKind(SyntaxKind.None))
                {
                    continue;
                }

                var line = directive switch
                {
                    { Alias: not null } => semanticModel.GetDeclaredSymbol(directive) is { } alias
                        ? $"using {directive.Alias.Name.Identifier.Text} = {alias.Target.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)};"
                        : null,
                    _ => semanticModel.GetSymbolInfo(directive.NamespaceOrType).Symbol is { } target
                        ? $"using {(directive.StaticKeyword.IsKind(SyntaxKind.None) ? string.Empty : "static ")}{target.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)};"
                        : null
                };
                if ((line is not null) && !usings.Contains(line))
                {
                    usings.Add(line);
                }
            }
        }

        return [.. usings];
    }

    // The field would clash with a member of the user, or with the field of a property with the same name declared earlier
    private static bool HasFieldConflict(INamedTypeSymbol containingType, string fieldName, IEnumerable<ISymbol> others, SyntaxNode syntax)
    {
        if (!containingType.GetMembers(fieldName).IsEmpty)
        {
            return true;
        }

        foreach (var other in others)
        {
            var location = other.Locations.FirstOrDefault(static x => x.IsInSource);
            if (location?.SourceTree is null)
            {
                continue;
            }

            var order = String.CompareOrdinal(location.SourceTree.FilePath, syntax.SyntaxTree.FilePath);
            if ((order < 0) || ((order == 0) && (location.SourceSpan.Start < syntax.SpanStart)))
            {
                return true;
            }
        }

        return false;
    }
}
